### ISSUE TITLE
Question: Sidecar and Testcontainers

### ISSUE THREAD

**Issue by christophwille** [riezebosch/Dapr.Wrapr#5]
This is more a general "Do you think it would be feasible / what problems do you see" type of question: I happened on

https://github.com/salaboy/dapr-testcontainers/blob/c2181fbd1041bf8e28398f9a0741644a38649ad6/Run.java#L30-L59

Given that Sidecar in Wrapr calls dapr cli, do you think something equivalent could be built via Testcontainers like above? Thanks for entertaining the idea.

**Comment by riezebosch** [comment]
I do like the idea! Now I need to play with it...

**Comment by riezebosch** [comment]
I think you don't need this package for that since you already control everything from the Testcontainer? You can even use the `client.WaitForSidecarAsync()` that's available on the SDK nowadays.
